spring:
  application:
    name: enrollment

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: jdbc:postgresql://localhost:5432/course_enrollment
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-256-bit-secret-key-here-change-it-in-production-123456
  expiration: 86400000

